# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVg-y6zve966oJ1T91YQuqxVjaU1jLmv
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

url_link = 'https://raw.githubusercontent.com/DeBugg14/te-sppu-lab/main/Mini-Projects/CovidVaccine/covid_vaccine_statewise.csv'
vaccine_df = pd.read_csv(url_link,index_col="Updated On", parse_dates=True)

vaccine_df.head()

vaccine_df.describe()

vaccine_df.info()

vaccine_df_by_State = vaccine_df.groupby('State')[['First Dose Administered','Second Dose Administered']].sum().reset_index()
vaccine_df_by_State

# Set the width and height of the figure
plt.figure(figsize=(10,6))

# Add title
plt.title("Female(Individuals Vaccinated)")

# Bar chart showing average arrival delay for Spirit Airlines flights by month
sns.barplot(x=vaccine_df.index, y=vaccine_df['Female(Individuals Vaccinated)'] )

# Add label for vertical axis
plt.ylabel("Female(Individuals Vaccinated)")

# Set the width and height of the figure
plt.figure(figsize=(10,6))

# Add title
plt.title("Male(Individuals Vaccinated)")

# Bar chart showing average arrival delay for Spirit Airlines flights by month
sns.barplot(x=vaccine_df.index, y=vaccine_df['Male(Individuals Vaccinated)'] )

# Add label for vertical axis
plt.ylabel("Male(Individuals Vaccinated)")